### ISSUE TITLE
Error logging in! [v1.0.3]

### ISSUE THREAD

**Issue by bachig26** [SaturnMusic/PC#4]
I always login via ARL Tokens and v1.0.3 doesn't let me to login.
so for now, I reverted back to v1.0.2.

### Screenshot

![Saturn_6zA3VeHH5i](https://github.com/user-attachments/assets/ee8785a0-8327-47d8-b65d-cf6baa089f42)

**Comment by bw8686** [comment]
We made a small mistake in an edit; a typo which has been fixed in the emergency v1.0.4 release.
